image: node:18

stages:
  - lint
  - test
  - deploy

cache:
  paths:
    - node_modules/

lint:
  stage: lint

  before_script:
    - yarn install --save-dev
  script:
    - yarn lint

test:
  stage: test

  before_script:
    - yarn install --save-dev

  script:
    - yarn run test:coverage

cc_coverage:
  stage: test
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'

  before_script:
    - yarn install --save-dev
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build

  script:
    - yarn run test:coverage

  after_script:
    - ./cc-test-reporter format-coverage -t lcov
    - ./cc-test-reporter upload-coverage -r $CC_TEST_REPORTER

publish:
  image: node:latest
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_PUBLISH_TOKEN}" > .npmrc
    - yarn run build
    - yarn publish --access public
